export const QUIZ_ACTIONS = {
  INITIALIZE_QUIZ_DATA: "INITIALIZE_QUIZ_DATA",
  SET_USER_SELECTED_OPTION: "SET_USER_SELECTED_OPTION",
  INCREASE_SCORE: "INCREASE_SCORE",
  RESET_QUIZ_STATE: "RESET_QUIZ_STATE",
  ADD_SCORE_TO_QUIZBOARD: "ADD_SCORE_TO_QUIZBOARD",
};
